gui:
  # Show borders around panels
  border: rounded
  showIcons: true
  theme:
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    unstagedChangesColor:
      - red
  commitLength:
    show: true
  nerdFontsVersion: "3"
